In [ ]:
#1.Q: Train Logistic Regression, Decision Tree, and Random Forest on the fruits.csv dataset and compare accuracy.
Weight (grams)    Size (cm)	  Color Score   Fruit Type
150               7.5           0.8          Apple
170               8.0           0.7          Apple
200               9.0           0.6          Orange
210               9.5           0.5          Orange
180               8.5           0.65         Apple

In [2]:
d= { "Weight (grams)": [150,170,200,210,180],
     "Size (cm)" : [7.5,8.0,9.0,9.5,8.5],
     "Color Score":[0.8,0.7,0.6,0.5,0.65],
     "Fruit Type"  :["Apple","Apple","Orange","Orange","Apple"]
   }
import pandas as pd
df=pd.DataFrame(d)
df

   Weight (grams)  Size (cm)  Color Score Fruit Type
0             150        7.5         0.80      Apple
1             170        8.0         0.70      Apple
2             200        9.0         0.60     Orange
3             210        9.5         0.50     Orange
4             180        8.5         0.65      Apple

In [3]:
df.columns

Index(['Weight (grams)', 'Size (cm)', 'Color Score', 'Fruit Type'], dtype='str')

In [4]:
x=df[['Weight (grams)', 'Size (cm)', 'Color Score']]
x

   Weight (grams)  Size (cm)  Color Score
0             150        7.5         0.80
1             170        8.0         0.70
2             200        9.0         0.60
3             210        9.5         0.50
4             180        8.5         0.65

In [5]:
y=df['Fruit Type']

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=0)
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

models=[LogisticRegression(),DecisionTreeClassifier(),RandomForestClassifier()]
accuracy=[]
for model in models:

    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    
    acc=accuracy_score(y_test,y_pred)
    accuracy.append(acc)

print(accuracy)

[1.0, 0.5, 0.5]

In [13]:
#2.Apply K-Means, DBSCAN, and Agglomerative Clustering on the following dataset and print cluster counts.
data = {
    "Annual_Income": [50, 55, 60, 65, 70],
    "Spending_Score": [40, 35, 70, 75, 80]
}

In [25]:
df=pd.DataFrame(data)
df

   Annual_Income  Spending_Score
0             50              40
1             55              35
2             60              70
3             65              75
4             70              80

In [30]:
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import DBSCAN

models =  [ KMeans(n_clusters=3),
          AgglomerativeClustering(n_clusters=3),
           DBSCAN()]
        
for model in models:
    clusters=model.fit_predict(df)
    print(f"{model} :{clusters}")

KMeans(n_clusters=3) :[1 1 0 0 2]
AgglomerativeClustering(n_clusters=3) :[1 1 0 0 2]
DBSCAN() :[-1 -1 -1 -1 -1]

In [33]:
#3.
#The dataset below contains information about houses. 
#Train and compare three regression models (Linear Regression, Decision Tree, Random Forest) to predict Price.
data = {
    "Area (sqft)": [850, 900, 1200, 1500, 1750, 2000, 2500, 2750, 3000],
    "Bedrooms": [2, 2, 3, 3, 4, 4, 4, 5, 5],
    "Age (years)": [5, 10, 8, 15, 20, 18, 12, 30, 25],
    "Price": [150000, 170000, 210000, 250000, 275000, 300000, 350000, 375000, 400000]
}

In [34]:
df=pd.DataFrame(data)
df

   Area (sqft)  Bedrooms  Age (years)   Price
0          850         2            5  150000
1          900         2           10  170000
2         1200         3            8  210000
3         1500         3           15  250000
4         1750         4           20  275000
5         2000         4           18  300000
6         2500         4           12  350000
7         2750         5           30  375000
8         3000         5           25  400000

In [35]:
df.columns

Index(['Area (sqft)', 'Bedrooms', 'Age (years)', 'Price'], dtype='str')

In [40]:
x=df[['Area (sqft)', 'Bedrooms', 'Age (years)']]
x
y=df['Price']
y
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=0)

In [48]:

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
models=[LinearRegression(),DecisionTreeRegressor(),RandomForestRegressor()]
rscore=[]
for model in models:
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    r=r2_score(y_test,y_pred)
    print(f"{model} : {r}")
    rscore.append(r)

#print(rscore)

LinearRegression() : 0.9925751820116644
DecisionTreeRegressor() : 0.888849682427664
RandomForestRegressor() : 0.9326931898376852
[0.9925751820116644, 0.888849682427664, 0.9326931898376852]

In [49]:
data = {
    "Credit Score": [600, 650, 700, 750, 800, 850, 500, 550, 580],
    "Income ($)": [40000, 50000, 60000, 80000, 100000, 120000, 25000, 30000, 35000],
    "Loan Amount": [20000, 25000, 30000, 35000, 40000, 45000, 15000, 20000, 22000],
    "Approval": [0, 0, 1, 1, 1, 1, 0, 0, 0]
}
df=pd.DataFrame(data)
df

   Credit Score  Income ($)  Loan Amount  Approval
0           600       40000        20000         0
1           650       50000        25000         0
2           700       60000        30000         1
3           750       80000        35000         1
4           800      100000        40000         1
5           850      120000        45000         1
6           500       25000        15000         0
7           550       30000        20000         0
8           580       35000        22000         0

In [50]:
df.columns

Index(['Credit Score', 'Income ($)', 'Loan Amount', 'Approval'], dtype='str')

In [53]:
x=df[['Credit Score', 'Income ($)', 'Loan Amount']]
x
y=df['Approval']
y
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=0)
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier